config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tutorials#index'
  resources :tutorials, only: [:new, :create, :edit, :update, :show, :destory]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :tutorial, optional: true

  before_save :downcase_fields

  def downcase_fields
    self.title.downcase!
  end
end

app/models/tag_programming.rb
class TagProgramming < ApplicationRecord
  has_many :tutorials
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  belongs_to :user
  belongs_to :tag_programming
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps,
                                allow_destroy: true,
                                # reject_if: proc { |att| att['tutorial_id'].blank? }
                                reject_if: :all_blank

  validates :title, presence: true
  before_save :downcase_fields

  def downcase_fields
    self.title.downcase!
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tutorials
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  enum level: {member: 0, admin: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery with: :exception
    rescue_from Pundit::NotAuthorizedError, with: :pundit_error
    before_action :configure_permited_parameters, if: :devise_controller?

    private

    def pundit_error
        flash[:notice] = 'Anda tidak memiliki hak akses'
        redirect_to root_path
    end

    def configure_permited_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController    
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    if params[:search]
      @tutorials = Tutorial.where('title like ?', "%#{params[:search]}%")
    else
      @tutorials = Tutorial.order(id: :desc)
    end

    @tutorials = @tutorials.paginate(per_page: 6, page: params[:page])
  end

  def show
    @tutorial = Tutorial.friendly.find(params[:id])
    @step_list = @tutorial.steps.order(no: :asc)
    @step = params[:step]

    if @step == params[:step]
      @get_body = @tutorial.steps.where(no: @step)
    end
  end

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = Tutorial.new(tutorial_params)
    @tutorial.user = current_user

    if @tutorial.save
      redirect_to @tutorial
    else
      render 'new'
    end
  end

  def edit
    @tutorial = Tutorial.friendly.find(params[:id])
    authorize @tutorial
  end

  def update
    @tutorial = Tutorial.friendly.find(params[:id])
    authorize @tutorial

    if @tutorial.update(tutorial_params)
      redirect_to @tutorial
    else
      render 'edit'
    end
  end

  def destroy
    @tutorial = Tutorial.friendly.find(params[:id])
    authorize @tutorial

    @tutorial.destroy
    redirect_to root_path, notice: 'Tutorial berhasil di hapus'
  end

  private

  def tutorial_params
    params.require(:tutorial).permit(:tag_programming_id, :title,
                                    steps_attributes: [:id, :_destroy, :tutorial_id, :no, :title, :body])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/application/_header.html.erb
<div class="app-header">
  <nav class="navbar navbar-light bg-light">
    <%= link_to image_tag('kedailogo.png', size: '46x46', id: 'logo') + ' Kedailabs' , root_path, class: 'navbar-brand' %>
    
    <div class="dropdown">
      <a class="btn-user btn btn-info dropdown-toggle" href='#' role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= user_signed_in? ? current_user.name : 'Halo teman' %>
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <% if user_signed_in? %>
          <%= link_to 'Keluar', destroy_user_session_path, { class: 'dropdown-item', method: 'delete' } %>
        <% else %>
          <%= link_to 'Daftar', new_user_registration_path, { class: 'dropdown-item' }%>
          <%= link_to 'Masuk', new_user_session_path, { class: 'dropdown-item' } %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/application/_image_condisi.erb
<% if tutorial.tag_programming_id == 1 %>
        <%= image_tag "icon/_0016_RUBY.jpg", class: 'img-fluid' %>
<% elsif tutorial.tag_programming_id == 2 %>
        <%= image_tag "icon/_0027_PHYTON.jpg", class: 'img-fluid' %>
<% elsif tutorial.tag_programming_id == 3 %>
        <%= image_tag "icon/_0031_JavaScript.jpg", class: 'img-fluid' %>
<% elsif tutorial.tag_programming_id == 4 %>
        <%= image_tag "icon/_0030_Java.jpg", class: 'img-fluid' %>
<% else %>
        <%= image_tag "icon/_0028_PHP.jpg", class: 'img-fluid' %>
<% end %>

app/views/application/_jumbotron.html.erb
<section class="app-jumbotron jumbotron">
    <div class="container">
        <h1 class="display-4">Selamat datang di Kedailabs!</h1>
        <p class="lead text-muted">Kedailabs merupakan salah satu fitur KedaiCoding yang menjadi
        tempat bagi para programmer dalam membagi pengetahuan melalui
        sebuah tutorial dalam proses pembuatan aplikasi, atau 
        menambahkan fitur baru kedalam aplikasi yang sudah ada.
        </p>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Kedailabs</title>
    <%= favicon_link_tag 'favicon.ico'%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render 'application/header' %>
      <% flash.each do |key, value| %>
        <div class="alert text-center alert-<%= key %> alert-dismissible fade show" role="alert">
          <%= value %>.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      
      <%= yield %>    
  </body>
</html>

app/views/tutorials/_form.html.erb
<% if @tutorial.errors.any? %>
<div class="alert alert-danger" role="alert">
  <ul>
    <% @tutorial.errors.full_messages.each do |error| %>
    <li>
      <%= error %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- form -->
<%= simple_form_for (@tutorial) do |f| %>
<div class="form-inputs">
  <%= f.label :tag_programming_id %><br>
  <%= f.collection_radio_buttons :tag_programming_id,
      [[1, 'Ruby'], [2, 'Python'], [3, 'JavaScript'], [4, 'Java'],[5, 'PHP']], 
      :first, :last %>
  <hr>

  <%= f.input :title, label: 'Judul' %>
  <hr>
</div>

<!-- nested-form steps -->
<div class='steps'>
  <%= f.simple_fields_for :steps do |builder| %>
  <!-- render partial step_fields -->
  <%= render 'step_fields', f: builder %>
  <% end %>
</div>
<!-- end nested-form -->

<div class="form-actions">
  <%= f.button :submit, class: 'btn btn-outline-success' %>
  <%= link_to_add_association 'Tambah Step', f, :steps, class: 'btn btn-outline-primary', data: { 
      association_insertion_node: '.steps', association_insertion_method: :append } %>
</div>
<% end %>
<!-- end form -->

app/views/tutorials/_step_body.html.erb
<% if step.present? %>
<div class="container">
    <strong><%= step %>.
    <% get_body.each do |gb| %>
        <%= gb.title.titleize %></strong><br>
        <%= sanitize gb.body %>
    <% end %>
<% else %>
    nill value
</div>
<% end %>

app/views/tutorials/_step_fields.html.erb
<div class="row nested-fields">
  <div class="col-md-2">
    <%= f.input :no, label: 'No', required: false %>
  </div>
  <div class="col-md-8">
    <%= f.input :title, label: 'Judul', required: false %>
  </div>
  <div class="col-md-2">
    <%= link_to_remove_association "hapus step", f, class: 'btn btn-outline-danger btn-sm btn-remove' %>
  </div>

  <div class="col-md-10 body">
    <%= f.input :body, label: 'Konten', as: :summernote %>
  </div>

</div>

app/views/tutorials/_step_list.html.erb
<ul>
    <% step_list.each do |sl| %>
    <li class="p-3 mb-2">
        <strong><%= link_to  "#{sl.no}. #{sl.title.titleize}" , {controller: 'tutorials', action: 'show', step: sl.no} %></strong>
    </li>
    <% end %>
</ul>

app/views/tutorials/edit.html.erb
<div class="container">
    <h1>Sunting Tutorial</h1>

    <%= render 'form', tutorial: @tutorial %>

    <div></div>
    <%= link_to 'Lihat', @tutorial, { class: 'btn btn-outline-info', style: '' } %>
    <%= link_to 'Kembali', root_path, { class: 'btn btn-outline-secondary'} %>
</div>

app/views/tutorials/index.html.erb
<!-- render partial jumbotron -->
<%= render 'application/jumbotron' %>

<nav class="navbar bg-transparent">
  <a class="buat-tutorial">
    <!-- tampilkan btn bila session user true -->
    <% if user_signed_in? %>
      <%= link_to 'Buat Tutorial', new_tutorial_path, { class: 'btn-buat btn btn-outline-success'} %>
    <% end %>
    <!-- end -->
  </a>
  <!-- form inline -->
  <%= form_tag root_path, method: :get, class: 'form-inline my-2 my-lg-0' do %>
  <div class="input-group">
    <div class="input-group-prepend">
      <!-- <i class=""> disini icon search </i> -->
    </div>
    <%= text_field_tag :search, nil, { class: 'form-control mr-sm-2', placeholder: 'Cari tutorial'} %>
    <%= submit_tag "Cari", class: 'btn btn-outline-success my-sm-0' %>
  </div>
  <% end %>
  <!-- end form inline -->
</nav>

<div class="container">
  <div class="row">
    <!-- each looping tutorial table -->
    <% @tutorials.each do |tutorial| %>
    <div class="col-md-4 card-deck">
      <!-- card list tutorial -->
      <div class="card bg-light" id="tutorial">
        <div class="card-body">
          <h5 class="card-title text-center">
            <%= tutorial.title.titleize %>
          </h5>
          <p class="card-text text-right">
            <small>
              Diperbarui
              <%= I18n.l (tutorial.updated_at.to_date) %>
              oleh
              <%= tutorial.user.name %>
            </small>
          </p>
          <%= render 'application/image_condisi.erb', tutorial: tutorial %>
          
          <%= link_to 'Mulai', tutorial_path(tutorial), class: 'btn tutorial-btn'%>
        </div>
      </div>
      <!-- end card -->
    </div>
    <% end %>
    <!-- end each -->
  </div>
  <br>
  <!-- pagination -->
  <%= will_paginate @tutorials, list_classes: %w(pagination justify-content-center),
                                  previous_label: '&laquo', next_label: '&raquo' %>
  <br>
</div>

app/views/tutorials/new.html.erb
<div class='container'>
    <h1 class="text-center">Buat Tutorial</h1><br>

    <%= render 'form', tutorial: @tutorial %>

    <%= link_to 'Back', root_path, class: 'btn btn-secondary btn-xs btn-back' %>
</div>

app/views/tutorials/show.html.erb
<!-- Nav tabs -->
<div class='row' id='step'>
  <div class='col-md-2' id='sidenav'>
    <%= render 'step_list', step_list: @step_list %>
  </div>

  <!-- Tab panes -->
  <div class='col-md-7 main' id='content'>
    <%= render 'step_body', get_body: @get_body, step: @step %>
  </div>

  <div class="col-md-3">
    <% if user_signed_in? %>
      <% if policy(@tutorial).edit? %>
      <%= link_to 'Sunting', edit_tutorial_path, { class: 'btn btn-outline-info btn-sm' } %>
      <% end %>
      <% if policy(@tutorial).destroy? %>
        <%= link_to 'Hapus', tutorial_path, method: :delete, data: {confirm: 'Apa anda yakin?'}, class: 'btn btn-outline-danger btn-sm' %>
      <% end %>
    <% end %>
    
  </div>
  <br>
</div>